<a href="https://colab.research.google.com/github/garradsimonel/IneuronAssignment/blob/main/Numpy_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Write a function so that the columns of the output matrix are powers of the input vector.


In [1]:
import numpy as np
from numpy.random import randint as ri
mat=ri(1,10,(5,5))
mat

array([[8, 5, 3, 3, 8],
       [6, 5, 7, 8, 5],
       [6, 9, 4, 3, 1],
       [3, 8, 2, 2, 7],
       [6, 4, 5, 5, 2]])

In [2]:
print("The output matrix will be powers of the Input matrix\n-------------\n",pow(mat,3))

The output matrix will be powers of the Input matrix
-------------
 [[512 125  27  27 512]
 [216 125 343 512 125]
 [216 729  64  27   1]
 [ 27 512   8   8 343]
 [216  64 125 125   8]]


Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [3]:
input=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
def movingavg(arr1,k):
  for j in range(0,arr1.size-k+1):
      yj=(j+(j+1)+(j+2)+(j+3))/k
      print("y",j,":",yj,"\n")
     
  

In [4]:
movingavg(input,3)

y 0 : 2.0 

y 1 : 3.3333333333333335 

y 2 : 4.666666666666667 

y 3 : 6.0 

y 4 : 7.333333333333333 

y 5 : 8.666666666666666 

y 6 : 10.0 

y 7 : 11.333333333333334 

y 8 : 12.666666666666666 

y 9 : 14.0 

y 10 : 15.333333333333334 

